In [2]:
# We create 1D ndarray that contains only integers
import numpy as np

X = np.array([1, 2, 3, 4, 5])

# We will print information about X
print(f"X =", X)
print("X has dimensions:", X.shape)
print("X is an object of type:", type(X))
print("The element in x are type:", X.dtype)

X = [1 2 3 4 5]
X has dimensions: (5,)
X is an object of type: <class 'numpy.ndarray'>
The element in x are type: int32


In [3]:
# we create 1d array that contain only strings
Y = np.array(['Sachin', 'Bista'])

print("Y =", Y)
print("Y has dimensions:", Y.shape)
print("Y is an object of type:", type(Y))
print("The element in Y are type:", Y.dtype)

Y = ['Sachin' 'Bista']
Y has dimensions: (2,)
Y is an object of type: <class 'numpy.ndarray'>
The element in Y are type: <U6


In [4]:
# we will create 1D that contain integer and strings
x = np.array([22, 27, "Sachin", "Bista"])

# print information about x
print("x = ", x)
print("x has dimensions:", x.shape)
print("x is an object of type:", type(x))
print("the element in x are type:", x.dtype)

x =  ['22' '27' 'Sachin' 'Bista']
x has dimensions: (4,)
x is an object of type: <class 'numpy.ndarray'>
the element in x are type: <U11


In [5]:
# using 1d of int and float
x = np.array([1, 2, 3, 4, 5])

y = np.array([1.2, 2.3, 3.4, 4.5, 5.6])

z = np.array([8, 2.3, 5.55])

print("the elements in x  are type of type:", x.dtype)
print("The elements in y are types of type:", y.dtype)
print("The elements in z are types of type:", z.dtype)


the elements in x  are type of type: int32
The elements in y are types of type: float64
The elements in z are types of type: float64


In [6]:
# Using a 1-D Array of Float, and specifying the datatype of each element as int64
x = np.array([1, 3, 4.5, 1.1, 3.3, 5.6], dtype = np.int64)
print(x)


[1 3 4 1 3 5]


In [7]:
# Using 2D array
Y = np.array([[1,2,3],[3,2,1],[4,5,6],[7,8,9]])

print("Y =", Y)

Y = [[1 2 3]
 [3 2 1]
 [4 5 6]
 [7 8 9]]
