### Creating the ML pipeline using train_test_split() -> Normalization -> model_training()

In [7]:
import numpy as np

X = np.array([
    [20, 20000],
    [25, 25000],
    [30, 30000],
    [35, 35000],
    [40, 40000],
    [45, 45000],
    [50, 50000],
    [55, 55000],
    [60, 60000],
    [65, 65000]
])

y = np.array([0,0,0,1,1,1,1,1,1,1])
print(X, y)

[[   20 20000]
 [   25 25000]
 [   30 30000]
 [   35 35000]
 [   40 40000]
 [   45 45000]
 [   50 50000]
 [   55 55000]
 [   60 60000]
 [   65 65000]] [0 0 0 1 1 1 1 1 1 1]


#### Think of column 1 as Age, Column 2 as Monthly Bill, column 3 as Churn
##### 0 - customer does not churn and 1 - Customer churns

### Step 2: Separate the training and testing data

In [8]:
# Import the scikit learn
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
print("X_train:")
print(X_train)

print("\nX_test")
print(X_test)

print("\n y_train")
print(y_train)


print("\nY_test")
print(y_test)


X_train:
[[   45 45000]
 [   20 20000]
 [   55 55000]
 [   30 30000]
 [   65 65000]
 [   40 40000]
 [   35 35000]
 [   50 50000]]

X_test
[[   60 60000]
 [   25 25000]]

 y_train
[1 0 1 0 1 1 1 1]

Y_test
[1 0]


In [11]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (8, 2)
X_test shape: (2, 2)
y_train shape: (8,)
y_test shape: (2,)
